<?php

$languageNames = array(
);

$currencyNames = array(
'AMD' => ''ARS' => 'Peso argjentin',
'ATS' => 'Selin austriac',
'AUD' => 'dolar australian',
'BEF' => 'Franc de Belgjiche',
'BIF' => 'Franc burundês',
'BND' => 'Dolar dal Brunei',
'BRL' => 'real brasilian',
'BYR' => 'Rubli bielorùs',
'CAD' => 'dolar canadês',
'CHF' => 'franc svuizar',
'CNY' => 'yuan cinês',
'CSD' => 'Vieri dinar serp',
'CUP' => 'Peso cuban',
'CZK' => 'Corone de Republiche Ceche',
'DEM' => 'Marc todesc',
'DKK' => 'corone danese',
'DZD' => 'Dinar algerin',
'EUR' => 'euro',
'FRF' => 'Franc francês',
'GBP' => 'sterline britaniche',
'HKD' => 'dolar di Hong Kong',
'HRD' => 'Dinar cravuat',
'HRK' => 'Kuna cravuate',
'IDR' => 'rupiah indonesiane',
'INR' => 'rupie indiane',
'IRR' => 'Rial iranian',
'ITL' => 'Lire taliane',
'JPY' => 'yen gjaponês',
'KRW' => 'won de Coree dal Sud',
'LVL' => 'Lats leton',
'MXN' => 'peso messican',
'NAD' => 'Dolar namibian',
'NIO' => 'Córdoba oro nicaraguan',
'NOK' => 'corone norvegjese',
'NZD' => 'Dollar neozelandês',
'PKR' => 'Rupie pachistane',
'PLN' => 'zloty polac',
'RSD' => 'Dinar serp',
'RUB' => 'rubli rus',
'SAR' => 'riyal de Arabie Saudite',
'SEK' => 'corone svedese',
'SIT' => 'Talar sloven',
'SKK' => 'Corone slovache',
'THB' => 'baht tailandês',
'TRL' => 'Viere Lire turche',
'TRY' => 'lire turche',
'TWD' => 'gnûf dolar taiwanês',
'USD' => 'dolar american',
'USN' => 'Dolar american (prossime zornade)',
'USS' => 'Dolar american (stesse zornade)',
'XAG' => 'Arint',
'XAU' => 'Aur',
'XBA' => 'Unitât composite europeane',
'XBB' => 'Unitât monetarie europeane',
'XBC' => 'Unitât di acont europeane (XBC)',
'XBD' => 'Unitât di acont europeane (XBD)',
'XDR' => 'Dirits speciâi di incas',
'XFO' => 'Franc aur francês',
'XFU' => 'Franc UIC francês',
'XPD' => 'Paladi',
'XPT' => 'Platin',
'XRE' => 'fonts RINET',
'XTS' => 'codiç di verifiche de monede',
'XXX' => 'Monede no valide o no cognossude',
'ZAR' => 'rand sudafrican',
);

$countryNames = array(
);
