<?php

/**
 * Comments indicate draft status (see <http://www.unicode.org/reports/tr35/#Common_Attributes>).
 * - contributed: partially approved by the technical committee.
 * - provisional: partially confirmed.
 * - unconfirmed: no confirmation available.
 * Language names without comments are fully approved by the technical committee.
 */
$languageNames = array(
'aa' => 'afarština',
'ab' => 'abcházština',
'ace' => 'acehština', #contributed
'ach' => 'ačoli', #contributed
'ada' => 'adangme', #contributed
'ady' => 'adygejština', #contributed
'ae' => 'avestánština', #contributed
'afa' => 'afroasijské jazyky', #contributed
'af' => 'afrikánština',
'afh' => 'afrihili', #contributed
'ain' => 'ainština', #contributed
'ak' => 'akanština', #contributed
'akk' => 'akkadština', #contributed
'ale' => 'aleutština', #contributed
'alg' => 'algonkinské jazyky', #contributed
'am' => 'amharština',
'an' => 'aragonština', #contributed
'ang' => 'staroangličtina', #contributed
'anp' => 'angika', #contributed
'apa' => 'apačské jazyky', #contributed
'ar' => 'arabština',
'arc' => 'aramejština', #contributed
'arn' => 'araukánština', #contributed
'arp' => 'arapažština', #contributed
'art' => 'umělé jazyky', #contributed
'arw' => 'arawacké jazyky', #contributed
'as' => 'asámština',
'ath' => 'athapaskánské jazyky', #contributed
'aus' => 'australské jazyky', #contributed
'av' => 'avarština', #contributed
'awa' => 'awadhština', #contributed
'ay' => 'ajmarština',
'az' => 'ázerbájdžánština',
'ba' => 'baškirština',
'bad' => 'banda', #contributed
'bai' => 'bamilek', #contributed
'bal' => 'balúčština', #contributed
'ban' => 'balijština', #contributed
'bas' => 'basa', #contributed
'bat' => 'baltské jazyky', #contributed
'be' => 'běloruština',
'bej' => 'bedža', #contributed
'bem' => 'bembština', #contributed
'ber' => 'berberské jazyky', #contributed
'bg' => 'bulharština',
'bh' => 'biharština',
'bho' => 'bhojpurština', #contributed
'bi' => 'bislamština',
'bik' => 'bikolština', #contributed
'bin' => 'bini', #contributed
'bla'  => 'siksika', #provisional
'bm' => 'bambarština', #contributed
'bn' => 'bengálština',
'bnt' => 'bantuské jazyky', #contributed
'bo' => 'tibetština',
'bra' => 'bradžština', #contributed
'br' => 'bretaňština',
'bs' => 'bosenština',
'btk' => 'batačtina', #contributed
'bua' => 'burjatština', #contributed
'bug' => 'bugiština', #contributed
'cad' => 'caddo', #contributed
'cai' => 'středoamerické indiánské jazyky', #contributed
'ca' => 'katalánština',
'car' => 'karibština', #contributed
'cau' => 'kavkazské jazyky', #contributed
'ceb' => 'cebuánština', #contributed
'ce' => 'čečenština', #contributed
'cel' => 'keltské jazyky', #contributed
'chb' => 'čibča', #contributed
'ch' => 'čamoro', #contributed
'chg' => 'čagatajština', #contributed
'chk' => 'čukština', #contributed
'chm' => 'marijština', #contributed
'chn' => 'činuk pidžin', #contributed
'cho' => 'čoktština', #contributed
'chp' => 'čipevajština', #contributed
'chr' => 'čerokézština', #contributed
'chy' => 'čejenština', #contributed
'cmc' => 'čamština', #contributed
'co' => 'korsičtina',
'cop' => 'koptština', #contributed
'cpe' => 'anglická kreolština či pidgin', #contributed
'cpf' => 'francouzská kreolština či pidgin', #contributed
'cpp' => 'portugalská kreolština či pidgin', #contributed
'crh' => 'krymská turečtina',
'cr' => 'kríjština', #contributed
'crp' => 'kreolština či pidgin', #contributed
'cs' => 'čeština',
'cus' => 'kúšitské jazyky', #contributed
'cu'  => 'staroslověnština', #provisional
'cv' => 'čuvaština', #contributed
'cy' => 'velština',
'da' => 'dánština',
'dak' => 'dakotština', #contributed
'day' => 'dajáčtina', #contributed
'de-ch' => 'švýcarská standardní němčina', #contributed
'del' => 'delawarština', #contributed
'de' => 'němčina',
'den'  => 'slave', #provisional
'dgr' => 'dogrib', #contributed
'din' => 'dinkština', #contributed
'doi'  => 'dórgí', #provisional
'dra' => 'drávidské jazyky', #contributed
'dua' => 'dualština', #contributed
'dum'  => 'středoholandština', #provisional
'dv' => 'divehi',
'dyu' => 'djula', #contributed
'dz' => 'dzongkä',
'ebu' => 'embu', #contributed
'ee' => 'eweština', #contributed
'efi' => 'efikština',
'egy' => 'egyptština stará', #contributed
'eka' => 'ekajuk', #contributed
'el' => 'řečtina',
'elx' => 'elamitština', #contributed
'en' => 'angličtina',
'en-au' => 'australská angličtina',
'en-ca' => 'anglicky (Kanada)', #contributed
'en-gb' => 'britská angličtina',
'enm'  => 'středoangličtina', #provisional
'en-us' => 'americká angličtina',
'eo' => 'esperanto',
'es' => 'španělština',
'es-419' => 'latinskoamerická španělština',
'es-es' => 'iberská španělština',
'et' => 'estonština',
'eu' => 'baskičtina',
'ewo' => 'ewondo', #contributed
'fan' => 'fang', #contributed
'fa' => 'perština',
'fat' => 'fantština', #contributed
'ff' => 'fulahština', #contributed
'fi' => 'finština',
'fil' => 'filipínština', #contributed
'fiu' => 'ugrofinské jazyky', #contributed
'fj' => 'fidžijština',
'fo' => 'faerština',
'fr' => 'francouzština',
'fr-ch' => 'švýcarská francouzština',
'frm'  => 'středofrancouzština', #provisional
'fro'  => 'starofrancouzština', #provisional
'fur' => 'furlandština', #contributed
'fy' => 'fríština',
'gaa'  => 'ga', #provisional
'ga' => 'irština',
'gay'  => 'gayo', #provisional
'gba'  => 'gbaja', #provisional
'gd' => 'skotská gaelština',
'gem' => 'germánské jazyky', #contributed
'gez'  => 'geez', #provisional
'gil' => 'kiribatština', #contributed
'gl' => 'galicijština',
'gmh' => 'hornoněmčina (středověká)', #contributed
'gn' => 'guaranština',
'goh' => 'hornoněmčina (stará)', #contributed
'gon' => 'góndština', #contributed
'gor' => 'gorontalo', #contributed
'got' => 'gótština', #contributed
'grb' => 'grebo', #contributed
'grc' => 'starořečtina', #contributed
'gsw' => 'němčina (Švýcarsko)',
'gu' => 'gudžarátština',
'gv' => 'manština',
'gwi'  => 'gwichʼin', #provisional
'ha' => 'hauština',
'hai' => 'haidština', #contributed
'haw' => 'havajština', #contributed
'he' => 'hebrejština',
'hi' => 'hindština',
'hil' => 'hiligaynonština', #contributed
'him' => 'himáčalština', #contributed
'hit' => 'chetitština', #contributed
'hmn' => 'hmongština', #contributed
'ho' => 'hiri motu', #contributed
'hr' => 'chorvatština',
'ht' => 'haitština',
'hu' => 'maďarština',
'hup' => 'hupa', #contributed
'hy' => 'arménština',
'hz' => 'hererština', #contributed
'ia' => 'interlingua',
'iba' => 'ibanština', #contributed
'id' => 'indonéština',
'ie' => 'interlingue',
'ig' => 'igboština',
'ijo'  => 'idžo', #provisional
'ik' => 'inupiakština',
'ilo' => 'ilokánština', #contributed
'inc' => 'indické jazyky', #contributed
'ine' => 'indoevropské jazyky', #contributed
'inh' => 'inguština', #contributed
'ira' => 'íránské jazyky', #contributed
'iro' => 'irokézské jazyky', #contributed
'is' => 'islandština',
'it' => 'italština',
'iu' => 'inuktitutština',
'ja' => 'japonština',
'jv' => 'javánština',
'kaa' => 'karakalpačtina', #contributed
'kab' => 'kabylština', #contributed
'kac' => 'kačijština', #contributed
'ka' => 'gruzínština',
'kam' => 'kambština', #contributed
'kar' => 'karenština', #contributed
'kaw' => 'kawi', #contributed
'kbd' => 'kabardinština', #contributed
'kea' => 'kapverdština', #contributed
'kg' => 'konžština', #contributed
'kha' => 'khásí', #contributed
'khi' => 'kojsanské jazyky', #contributed
'kho' => 'chotánština', #contributed
'ki' => 'kikujština', #contributed
'kj' => 'kuaňamština', #contributed
'kk' => 'kazachština',
'kl' => 'grónština',
'kmb'  => 'kimbundština', #provisional
'km' => 'kambodžština',
'kn' => 'kannadština',
'kok' => 'konkánština', #contributed
'ko' => 'korejština',
'kos' => 'kosrajština', #contributed
'kpe'  => 'kpelle', #provisional
'kr'  => 'kanuri', #provisional
'kro'  => 'kru', #provisional
'kru' => 'kuruchština', #contributed
'ks' => 'kašmírština',
'ku' => 'kurdština',
'kum' => 'kumykština', #contributed
'kut'  => 'kutenai', #provisional
'kv'  => 'komijština', #provisional
'kw' => 'kornština', #contributed
'ky' => 'kyrgyzština',
'lad'  => 'ladinština', #provisional
'lah'  => 'lahndština', #provisional
'la' => 'latina',
'lam' => 'lambština', #contributed
'lb' => 'lucemburština',
'lez' => 'lezginština', #contributed
'lg'  => 'ganda', #provisional
'ln' => 'lingalština',
'lo' => 'laoština',
'lol' => 'mongština', #contributed
'loz'  => 'lozština', #provisional
'lt' => 'litevština',
'lua' => 'luba-luluaština', #contributed
'lui' => 'luiseňo', #contributed
'lu' => 'lubu-katanžština', #contributed
'lun' => 'lundština', #contributed
'luo' => 'luoština', #contributed
'lus'  => 'lišáí', #provisional
'luy' => 'luhja', #contributed
'lv' => 'lotyština',
'mad' => 'madurština', #contributed
'mag' => 'magahijština', #contributed
'mai' => 'maithiliština', #contributed
'mak'  => 'makasarština', #provisional
'man'  => 'mandingština', #provisional
'map' => 'austronéské jazyky', #contributed
'mas' => 'masajština', #contributed
'mdr'  => 'mandar', #provisional
'men'  => 'mende', #provisional
'mga'  => 'středoirština', #provisional
'mg' => 'malgaština',
'mh' => 'maršálština', #contributed
'mic'  => 'micmac', #provisional
'mi' => 'maorština',
'min'  => 'minangkabau', #provisional
'mis' => 'různé jazyky', #contributed
'mkh'  => 'mon-khmerské jazyky', #provisional
'mk' => 'makedonština',
'ml' => 'malabarština',
'mnc' => 'mandžuština', #contributed
'mni' => 'manipurština', #contributed
'mn' => 'mongolština',
'mno'  => 'manobo jazyky', #provisional
'moh'  => 'mohawk', #provisional
'mo' => 'moldavština',
'mos'  => 'mosi', #provisional
'mr' => 'maráthština',
'ms' => 'malajština',
'mt' => 'maltština',
'mul'  => 'složené (víceřádkové) jazyky', #provisional
'mun'  => 'mundské jazyky', #provisional
'mus'  => 'muskogee (creek)', #unconfirmed
'mwr'  => 'márvárština', #provisional
'my' => 'barmština',
'myn'  => 'mayské jazyky', #provisional
'nah' => 'nahuatl', #contributed
'nai' => 'severoamerické indiánské jazyky', #contributed
'na' => 'naurština',
'nap'  => 'neapolština', #provisional
'nb' => 'norština (bokmål)',
'nd' => 'ndebele (Zimbabwe)',
'nds'  => 'dolnoněmčina', #provisional
'ne' => 'nepálština',
'new'  => 'névárština', #provisional
'ng'  => 'ndondština', #provisional
'nia'  => 'nias', #provisional
'nic'  => 'nigero-kordofánské jazyky', #provisional
'niu' => 'niueština', #contributed
'nl' => 'nizozemština',
'nl-be' => 'vlámština',
'nn' => 'norština (nynorsk)',
'non'  => 'norština historická', #provisional
'no' => 'norština',
'nr' => 'ndebele (Jižní Afrika)',
'nso' => 'severní sotština',
'nub' => 'núbijské jazyky', #contributed
'nv' => 'navažština', #contributed
'nym' => 'ňamwežština', #contributed
'ny' => 'ňandžština',
'nyn'  => 'nyakolština', #provisional
'nyo'  => 'nyorština', #provisional
'nzi'  => 'nzima', #provisional
'oc' => 'okcitánština',
'oj' => 'odžibvejština', #contributed
'om' => 'oromština (Afan)',
'or' => 'urijština',
'osa'  => 'osage', #provisional
'os' => 'osetština',
'ota' => 'osmanská turečtina', #contributed
'oto'  => 'otomijské jazyky', #provisional
'paa' => 'papuánské jazyky', #contributed
'pag' => 'pangasinanština', #contributed
'pal'  => 'pahlaví', #provisional
'pam'  => 'papangau', #provisional
'pa' => 'paňdžábština',
'pap' => 'papiamento', #contributed
'pau' => 'palauština', #contributed
'peo'  => 'staroperština', #provisional
'phi' => 'filipínské jazyky', #contributed
'phn' => 'féničtina', #contributed
'pi' => 'pálí', #contributed
'pl' => 'polština',
'pon' => 'pohnpeiština', #contributed
'pra' => 'prákrtské jazyky', #contributed
'pro'  => 'provensálština', #provisional
'ps' => 'paštština',
'pt' => 'portugalština',
'pt-br' => 'brazilská portugalština',
'pt-pt' => 'iberská portugalština',
'qu' => 'kečuánština',
'raj' => 'rádžastánština', #contributed
'rap'  => 'rapanuiština', #provisional
'rar' => 'rarotongaština', #contributed
'rm' => 'rétorománština',
'rn' => 'kirundština',
'roa'  => 'románské jazyky', #provisional
'rof' => 'rombo', #contributed
'rom' => 'romština', #contributed
'ro' => 'rumunština',
'ru' => 'ruština',
'rw' => 'kinyarwandština',
'rwk' => 'rwa', #contributed
'sad'  => 'sandawština', #provisional
'sah'  => 'jakutština', #provisional
'sai'  => 'jihoamerické indiánské jazyky', #provisional
'sal' => 'sališské jazyky', #contributed
'sam' => 'samarština', #contributed
'sa' => 'sanskrt',
'sas' => 'sasakština', #contributed
'sat' => 'santálština', #contributed
'sco' => 'skotština', #contributed
'sc' => 'sardština', #contributed
'sd' => 'sindhština',
'sel'  => 'selkupština', #provisional
'sem'  => 'semitské jazyky', #provisional
'se' => 'severní sámština',
'sga'  => 'staroirština', #provisional
'sgn'  => 'znakové jazyky', #provisional
'sg' => 'sangština',
'shn'  => 'šanština', #provisional
'sh' => 'srbochorvatština',
'sid'  => 'sidamo', #provisional
'sio'  => 'siouxské jazyky', #provisional
'si' => 'sinhálština',
'sit' => 'tibetočínské jazyky', #contributed
'sk' => 'slovenština',
'sla' => 'slovanský jazyk', #contributed
'sl' => 'slovinština',
'smi' => 'sámské jazyky', #contributed
'sm' => 'samojština',
'snk'  => 'sonikština', #provisional
'sn' => 'šonština',
'sog'  => 'sogdština', #provisional
'son' => 'songhajština', #contributed
'so' => 'somálština',
'sq' => 'albánština',
'srr' => 'sererština', #contributed
'sr' => 'srbština',
'ssa' => 'nilosaharské jazyky', #contributed
'ss' => 'siswatština',
'st' => 'sesotho',
'suk'  => 'sukuma', #provisional
'sus'  => 'susu', #provisional
'su' => 'sundanština',
'sux' => 'sumerština', #contributed
'sv' => 'švédština',
'swb' => 'komorština', #contributed
'sw' => 'svahilština',
'syr' => 'syrština', #contributed
'tai'  => 'thajské jazyky', #provisional
'ta' => 'tamilština',
'tem'  => 'temne', #provisional
'ter'  => 'tereno', #provisional
'te' => 'telugština',
'tet' => 'tetumština',
'tg' => 'tádžičtina',
'th' => 'thajština',
'tig' => 'tigrejština', #contributed
'ti' => 'tigrinijština',
'tiv'  => 'tivština', #provisional
'tkl' => 'tokelauština', #contributed
'tk' => 'turkmenština',
'tlh' => 'klingonština', #contributed
'tli'  => 'tlingit', #provisional
'tl' => 'tagalog',
'tmh'  => 'tamašek', #provisional
'tn' => 'setswanština',
'to' => 'tonga',
'tpi' => 'tok pisin', #contributed
'tr' => 'turečtina',
'tsi' => 'tsimšijské jazyky', #contributed
'ts' => 'tsonga',
'tt' => 'tatarština',
'tum' => 'tumbukština', #contributed
'tut' => 'altajské jazyky', #contributed
'tvl' => 'tuvalština', #contributed
'tw' => 'twi',
'ty' => 'tahitština', #contributed
'tyv' => 'tuvinština', #contributed
'udm' => 'udmurtština', #contributed
'uga' => 'ugaritština', #contributed
'ug' => 'ujgurština',
'uk' => 'ukrajinština',
'umb'  => 'umbundu', #provisional
'und' => 'neznámý nebo neplatný jazyk',
'ur' => 'urdština',
'uz' => 'uzbečtina',
'vai'  => 'vai', #provisional
've' => 'venda', #contributed
'vi' => 'vietnamština',
'vot'  => 'votiatština', #provisional
'vo' => 'volapuk',
'wae' => 'němčina (walser)', #contributed
'wak' => 'wakašské jazyky', #contributed
'wal' => 'walamština', #contributed
'war'  => 'waray', #provisional
'was' => 'waština', #contributed
'wa' => 'valonština', #contributed
'wen' => 'lužickosrbské jazyky', #contributed
'wo' => 'wolofština',
'xal' => 'kalmyčtina', #contributed
'xh' => 'xhoština',
'yao' => 'jaoština', #contributed
'yap'  => 'yapese', #provisional
'yi' => 'jidiš',
'yo' => 'jorubština',
'ypk'  => 'yupik', #provisional
'yue' => 'kantonština', #contributed
'za' => 'čuangština',
'zap' => 'zapotéčtina', #contributed
'zen'  => 'zenaga', #provisional
'zh' => 'čínština',
'zh-hans' => 'čínština (zjednodušená)',
'znd'  => 'zandština', #provisional
'zun' => 'zunijština', #contributed
'zu' => 'zuluština',
'zxx' => 'žádný jazykový obsah', #contributed
);

$currencyNames = array(
'ADP' => 'andorrská peseta',
'AED' => 'SAE dirham',
'AFA' => 'afghánský afghán (1927-2002)',
'AFN' => 'afghánský afghán',
'ALK' => 'albánské lek (1946-1965)',
'ALL' => 'albánský lek',
'AMD' => 'arménský dram',
'ANG' => 'zlatý Nizozemských Antil',
'AOA' => 'angolská kwanza',
'AOK' => 'angolská kwanza (1977-1991)',
'AON' => 'angolská kwanza (1990-2000)',
'AOR' => 'angolská kwanza (1995-1999)',
'ARA' => 'argentinský austral',
'ARP' => 'argentinské peso (1983-1985)',
'ARS' => 'argentinské peso',
'ATS' => 'rakouský šilink',
'AUD' => 'australský dolar',
'AWG' => 'arubský zlatý',
'AZM' => 'ázerbájdžánský manat (1993-2006)',
'AZN' => 'Ázerbajdžánský manat',
'BAD' => 'bosenský dinár (1992-1994)',
'BAM' => 'bosenská konvertibilní marka',
'BAN' => 'bosenský nový dinár (1994-1997)',
'BBD' => 'barbadoský dolar',
'BDT' => 'bangladéšská taka',
'BEC' => 'belgický konvertibilní frank',
'BEF' => 'belgický frank',
'BEL' => 'belgický finanční frank',
'BGN' => 'bulharský lev',
'BHD' => 'bahrajnský dinár',
'BIF' => 'burundský frank',
'BMD' => 'bermudský dolar',
'BND' => 'brunejský dolar',
'BOB' => 'bolivijský boliviano',
'BOL' => 'bolivijský boliviano (1863-1963)',
'BOP' => 'bolivijské peso',
'BOV' => 'bolivijský mvdol',
'BRL' => 'brazilský real',
'BSD' => 'bahamský dolar',
'BTN' => 'bhútánský ngultrum',
'BUK' => 'barmský kyat',
'BWP' => 'botswanská pula',
'BYB' => 'běloruský rubl (1994-1999)',
'BYR' => 'běloruský rubl',
'BZD' => 'belizský dolar',
'CAD' => 'kanadský dolar',
'CDF' => 'konžský frank',
'CHF' => 'švýcarský frank',
'CLE' => 'chilské escudo',
'CLP' => 'chilské peso',
'CNY' => 'čínský jüan',
'COP' => 'kolumbijské peso',
'CRC' => 'kostarický colón',
'CSK' => 'československá koruna',
'CUC' => 'Kubánské konvertibilní peso',
'CUP' => 'kubánské peso',
'CVE' => 'kapverdské escudo',
'CYP' => 'kyperská libra',
'CZK' => 'česká koruna',
'DDM' => 'východoněmecká marka',
'DEM' => 'německá marka',
'DJF' => 'džibutský frank',
'DKK' => 'dánská koruna',
'DOP' => 'dominikánské peso',
'DZD' => 'alžírský dinár',
'EEK' => 'estonská koruna',
'EGP' => 'egyptská libra',
'ERN' => 'eritrejská nakfa',
'ESA' => 'španělská peseta („A“ účet)',
'ESB' => 'španělská peseta (konvertibilní účet)',
'ESP' => 'španělská peseta',
'ETB' => 'etiopský birr',
'EUR' => 'euro',
'FIM' => 'finská marka',
'FJD' => 'fidžijský dolar',
'FKP' => 'falklandská libra',
'FRF' => 'francouzský frank',
'GBP' => 'britská libra',
'GEL' => 'gruzínské lari',
'GHC' => 'ghanský cedi (1979-2007)',
'GHS' => 'ghanský cedi',
'GIP' => 'gibraltarská libra',
'GMD' => 'gambijský dalasi',
'GNF' => 'guinejský frank',
'GNS' => 'guinejský syli',
'GRD' => 'řecká drachma',
'GTQ' => 'guatemalský quetzal',
'GWP' => 'guinea-bissauské peso',
'GYD' => 'guyanský dolar',
'HKD' => 'hongkongský dolar',
'HNL' => 'honduraská lempira',
'HRD' => 'chorvatský dinár',
'HRK' => 'chorvatská kuna',
'HTG' => 'haitský gourde',
'HUF' => 'maďarský forint',
'IDR' => 'indonéská rupie',
'IEP' => 'irská libra',
'ILP' => 'izraelská libra',
'ILR' => 'izraelský šekel (1980-1985)',
'ILS' => 'izraelský nový šekel',
'INR' => 'indická rupie',
'IQD' => 'irácký dinár',
'IRR' => 'íránský rijál',
'ISJ' => 'islandská koruna (1918-1981)',
'ISK' => 'islandská koruna',
'ITL' => 'italská lira',
'JMD' => 'jamajský dolar',
'JOD' => 'jordánský dinár',
'JPY' => 'japonský jen',
'KES' => 'keňský šilink',
'KGS' => 'kyrgyzský som',
'KHR' => 'kambodžský riel',
'KMF' => 'komorský frank',
'KPW' => 'severokorejský won',
'KRW' => 'jihokorejský won',
'KWD' => 'kuvajtský dinár',
'KYD' => 'kajmanský dolar',
'KZT' => 'kazašské tenge',
'LAK' => 'laoský kip',
'LBP' => 'libanonská libra',
'LKR' => 'srílanská rupie',
'LRD' => 'liberijský dolar',
'LSL' => 'lesothský loti',
'LTL' => 'litevský litas',
'LTT' => 'litevský talonas',
'LUC' => 'lucemburský konvertibilní frank',
'LUF' => 'lucemburský frank',
'LUL' => 'lucemburský finanční frank',
'LVL' => 'lotyšský lat',
'LVR' => 'lotyšský rubl',
'LYD' => 'libyjský dinár',
'MAD' => 'marocký dinár',
'MAF' => 'marocký frank',
'MDL' => 'moldavský lei',
'MGA' => 'madagaskarský ariary',
'MGF' => 'madagaskarský frank',
'MKD' => 'makedonský denár',
'MKN' => 'makedonský denár (1992-1993)',
'MLF' => 'malijský frank',
'MMK' => 'myanmarský kyat',
'MNT' => 'mongolský tugrik',
'MOP' => 'macajská pataca',
'MRO' => 'mauritánská ouguiya',
'MTL' => 'maltská lira',
'MTP' => 'maltská libra',
'MUR' => 'mauricijská rupie',
'MVR' => 'maledivská rupie',
'MWK' => 'malawijská kwacha',
'MXN' => 'mexické peso',
'MXP' => 'mexické stříbrné peso (1861-1992)',
'MYR' => 'malajsijský ringgit',
'MZE' => 'mosambický escudo',
'MZM' => 'mosambický metical (1980-2006)',
'MZN' => 'mozambický metical',
'NAD' => 'namibijský dolar',
'NGN' => 'nigerijská naira',
'NIC' => 'nikaragujská córdoba (1988-1991)',
'NIO' => 'nikaragujská córdoba',
'NOK' => 'norská koruna',
'NPR' => 'nepálská rupie',
'NZD' => 'novozélandský dolar',
'OMR' => 'ománský rijál',
'PAB' => 'panamská balboa',
'PEI' => 'peruánská inti',
'PEN' => 'peruánský nový sol',
'PES' => 'peruánský sol (1863-1965)',
'PGK' => 'papuánská nová kina',
'PHP' => 'filipínské peso',
'PKR' => 'pákistánská rupie',
'PLN' => 'polský zlotý',
'PLZ' => 'polský zlotý (1950-1995)',
'PTE' => 'portugalské escudo',
'PYG' => 'paraguajské guarani',
'QAR' => 'katarský rijál',
'RHD' => 'rhodéský dolar',
'ROL' => 'rumunské leu (1952-2006)',
'RON' => 'rumunské leu',
'RSD' => 'srbský dinár',
'RUB' => 'ruský rubl',
'RUR' => 'ruský rubl (1991-1998)',
'RWF' => 'rwandský frank',
'SAR' => 'saúdský rijál',
'SBD' => 'šalamounský dolar',
'SCR' => 'seychelská rupie',
'SDD' => 'súdánský dinár (1992-2007)',
'SDG' => 'Súdánská libra',
'SDP' => 'súdánská libra (1957-1998)',
'SEK' => 'švédská koruna',
'SGD' => 'singapurský dolar',
'SHP' => 'svatohelenská libra',
'SIT' => 'slovinský tolar',
'SKK' => 'slovenská koruna',
'SLL' => 'sierro-leonský leone',
'SOS' => 'somálský šilink',
'SRD' => 'Surinamský dolar',
'SRG' => 'surinamský zlatý',
'STD' => 'svatotomášská dobra',
'SUR' => 'sovětský rubl',
'SVC' => 'salvadorský colón',
'SYP' => 'syrská libra',
'SZL' => 'svazijský lilangeni',
'THB' => 'thajský baht',
'TJR' => 'tádžický rubl',
'TJS' => 'tádžické somoni',
'TMM' => 'turkmenský manat (1993-2009)',
'TMT' => 'turkmenský manat',
'TND' => 'tuniský dinár',
'TOP' => 'tonžská paanga',
'TPE' => 'timorské escudo',
'TRL' => 'turecká lira (1922-2005)',
'TRY' => 'turecká lira',
'TTD' => 'trinidadský dolar',
'TWD' => 'tchajwanský nový dolar',
'TZS' => 'tanzanský šilink',
'UAH' => 'ukrajinská hřivna',
'UAK' => 'ukrajinský karbovanec',
'UGS' => 'ugandský šilink (1966-1987)',
'UGX' => 'ugandský šilink',
'USD' => 'americký dolar',
'USN' => 'americký dolar (příští den)',
'USS' => 'americký dolar (týž den)',
'UYP' => 'uruguayské peso (1975-1993)',
'UYU' => 'uruguayské peso',
'UZS' => 'uzbecký sum',
'VEB' => 'venezuelský bolívar (1871-2008)',
'VEF' => 'venezuelský bolívar',
'VND' => 'vietnamský dong',
'VNN' => 'vietnamský dong (1978-1985)',
'VUV' => 'vanuatský vatu',
'WST' => 'samojská tala',
'XAF' => 'CFA/BEAC frank',
'XAG' => 'stříbro',
'XAU' => 'zlato',
'XBA' => 'evropská smíšená jednotka',
'XBB' => 'evropská peněžní jednotka',
'XBC' => 'evropská jednotka účtu 9 (XBC)',
'XBD' => 'evropská jednotka účtu 17 (XBD)',
'XCD' => 'východokaribský dolar',
'XDR' => 'SDR',
'XEU' => 'evropská měnová jednotka',
'XFO' => 'francouzský zlatý frank',
'XFU' => 'francouzský UIC frank',
'XOF' => 'CFA/BCEAO frank',
'XPF' => 'CFP frank',
'XPT' => 'platina',
'XTS' => 'kód zvlášť vyhrazený pro testovací účely',
'XXX' => 'neznámá měna',
'YDD' => 'jemenský dinár',
'YER' => 'jemenský rijál',
'YUD' => 'jugoslávský dinár (1966-1990)',
'YUM' => 'jugoslávský nový dinár (1994-2002)',
'YUN' => 'jugoslávský konvertibilní dinár (1990-1992)',
'ZAL' => 'jihoafrický finanční rand',
'ZAR' => 'jihoafrický rand',
'ZMK' => 'zambijská kwacha',
'ZRN' => 'zairský nový zaire (1993-1998)',
'ZRZ' => 'zairský zaire (1971-1993)',
'ZWD' => 'zimbabwský dolar (1980-2008)',
'ZWL' => 'zimbabwský dolar (2009)',
'ZWR' => 'zimbabwský dolar (2008)',
);

$countryNames = array(
'AC' => 'Ostrov Ascension',
'AD' => 'Andorra',
'AE' => 'Spojené arabské emiráty',
'AF' => 'Afghánistán',
'AG' => 'Antigua a Barbuda',
'AI' => 'Anguilla',
'AL' => 'Albánie',
'AM' => 'Arménie',
'AN' => 'Nizozemské Antily',
'AO' => 'Angola',
'AQ' => 'Antarktida',
'AR' => 'Argentina',
'AS' => 'Americká Samoa',
'AT' => 'Rakousko',
'AU' => 'Austrálie',
'AW' => 'Aruba',
'AX' => 'Alandy',
'AZ' => 'Ázerbájdžán',
'BA' => 'Bosna a Hercegovina',
'BB' => 'Barbados',
'BD' => 'Bangladéš',
'BE' => 'Belgie',
'BF' => 'Burkina Faso',
'BG' => 'Bulharsko',
'BH' => 'Bahrajn',
'BI' => 'Burundi',
'BJ' => 'Benin',
'BL' => 'Svatý Bartoloměj',
'BM' => 'Bermudy',
'BN' => 'Brunej',
'BO' => 'Bolívie',
'BR' => 'Brazílie',
'BS' => 'Bahamy',
'BT' => 'Bhútán',
'BV' => 'Bouvetův ostrov',
'BW' => 'Botswana',
'BY' => 'Bělorusko',
'BZ' => 'Belize',
'CA' => 'Kanada',
'CC' => 'Kokosové ostrovy',
'CD' => 'Kongo - Kinshasa',
'CF' => 'Středoafrická republika',
'CG' => 'Kongo - Brazzaville',
'CH' => 'Švýcarsko',
'CI' => 'Pobřeží slonoviny',
'CK' => 'Cookovy ostrovy',
'CL' => 'Chile',
'CM' => 'Kamerun',
'CN' => 'Čína',
'CO' => 'Kolumbie',
'CP' => 'Clippertonův ostrov',
'CR' => 'Kostarika',
'CS' => 'Srbsko aČerná Hora',
'CU' => 'Kuba',
'CV' => 'Kapverdy',
'CX' => 'Vánoční ostrovy',
'CY' => 'Kypr',
'CZ' => 'Česká republika',
'DE' => 'Německo',
'DJ' => 'Džibutsko',
'DK' => 'Dánsko',
'DM' => 'Dominika',
'DO' => 'Dominikánská republika',
'DZ' => 'Alžírsko',
'EA' => 'Ceuta a Melilla',
'EC' => 'Ekvádor',
'EE' => 'Estonsko',
'EG' => 'Egypt',
'EH' => 'Západní Sahara',
'ER' => 'Eritrea',
'ES' => 'Španělsko',
'ET' => 'Etiopie',
'EU' => 'Evropská unie',
'FI' => 'Finsko',
'FJ' => 'Fidži',
'FK' => 'Falklandské ostrovy',
'FM' => 'Mikronésie',
'FO' => 'Faerské ostrovy',
'FR' => 'Francie',
'GA' => 'Gabon',
'GB' => 'Velká Británie',
'GD' => 'Grenada',
'GE' => 'Gruzie',
'GF' => 'Francouzská Guyana',
'GG' => 'Guernsey',
'GH' => 'Ghana',
'GI' => 'Gibraltar',
'GL' => 'Grónsko',
'GM' => 'Gambie',
'GN' => 'Guinea',
'GP' => 'Guadeloupe',
'GQ' => 'Rovníková Guinea',
'GR' => 'Řecko',
'GS' => 'Jižní Georgie a Jižní Sandwichovy ostrovy',
'GT' => 'Guatemala',
'GU' => 'Guam',
'GW' => 'Guinea-Bissau',
'GY' => 'Guyana',
'HK' => 'Hongkong - zvláštní administrativní oblast Číny',
'HK' => 'Hongkong',
'HM' => 'Heardův ostrov a McDonaldovy ostrovy',
'HN' => 'Honduras',
'HR' => 'Chorvatsko',
'HT' => 'Haiti',
'HU' => 'Maďarsko',
'IC' => 'Kanárské ostrovy',
'ID' => 'Indonésie',
'IE' => 'Irsko',
'IL' => 'Izrael',
'IM' => 'Ostrov Man',
'IN' => 'Indie',
'IO' => 'Britské indickooceánské území',
'IQ' => 'Irák',
'IR' => 'Írán',
'IS' => 'Island',
'IT' => 'Itálie',
'JE' => 'Jersey',
'JM' => 'Jamajka',
'JO' => 'Jordánsko',
'JP' => 'Japonsko',
'KE' => 'Keňa',
'KG' => 'Kyrgyzstán',
'KH' => 'Kambodža',
'KI' => 'Kiribati',
'KM' => 'Komory',
'KN' => 'Svatý Kitts a Nevis',
'KP' => 'Severní Korea',
'KR' => 'Jižní Korea',
'KW' => 'Kuvajt',
'KY' => 'Kajmanské ostrovy',
'KZ' => 'Kazachstán',
'LA' => 'Laos',
'LB' => 'Libanon',
'LC' => 'Svatá Lucie',
'LI' => 'Lichtenštejnsko',
'LK' => 'Srí Lanka',
'LR' => 'Libérie',
'LS' => 'Lesotho',
'LT' => 'Litva',
'LU' => 'Lucembursko',
'LV' => 'Lotyšsko',
'LY' => 'Libye',
'MA' => 'Maroko',
'MC' => 'Monako',
'MD' => 'Moldavsko',
'ME' => 'Černá Hora',
'MG' => 'Madagaskar',
'MH' => 'Marshallovy ostrovy',
'MK' => 'Makedonie',
'ML' => 'Mali',
'MM' => 'Myanmar',
'MN' => 'Mongolsko',
'MO' => 'Macao - zvláštní administrativní oblast Číny',
'MO' => 'Macao',
'MP' => 'Severní Mariany',
'MQ' => 'Martinik',
'MR' => 'Mauritánie',
'MS' => 'Montserrat',
'MT' => 'Malta',
'MU' => 'Mauricius',
'MV' => 'Maledivy',
'MW' => 'Malawi',
'MX' => 'Mexiko',
'MY' => 'Malajsie',
'MZ' => 'Mosambik',
'NA' => 'Namibie',
'NC' => 'Nová Kaledonie',
'NE' => 'Niger',
'NF' => 'Norfolk',
'NG' => 'Nigérie',
'NI' => 'Nikaragua',
'NL' => 'Nizozemsko',
'NO' => 'Norsko',
'NP' => 'Nepál',
'NR' => 'Nauru',
'NU' => 'Niue',
'NZ' => 'Nový Zéland',
'OM' => 'Omán',
'PA' => 'Panama',
'PE' => 'Peru',
'PF' => 'Francouzská Polynésie',
'PG' => 'Papua-Nová Guinea',
'PH' => 'Filipíny',
'PK' => 'Pákistán',
'PL' => 'Polsko',
'PM' => 'Svatý Pierre a Miquelon',
'PN' => 'Pitcairnovy ostrovy',
'PR' => 'Portoriko',
'PS' => 'Palestinská území',
'PT' => 'Portugalsko',
'PW' => 'Palau',
'PY' => 'Paraguay',
'QA' => 'Katar',
'QO' => 'Vnější Oceánie',
'RE' => 'Réunion',
'RO' => 'Rumunsko',
'RS' => 'Srbsko',
'RU' => 'Rusko',
'RW' => 'Rwanda',
'SA' => 'Saúdská Arábie',
'SB' => 'Šalamounovy ostrovy',
'SC' => 'Seychely',
'SD' => 'Súdán',
'SE' => 'Švédsko',
'SG' => 'Singapur',
'SH' => 'Svatá Helena',
'SI' => 'Slovinsko',
'SJ' => 'Špicberky a Jan Mayen',
'SK' => 'Slovensko',
'SL' => 'Sierra Leone',
'SM' => 'San Marino',
'SN' => 'Senegal',
'SO' => 'Somálsko',
'SR' => 'Surinam',
'ST' => 'Svatý Tomáš',
'SV' => 'Salvador',
'SY' => 'Sýrie',
'SZ' => 'Svazijsko',
'TA' => 'Tristan da Cunha',
'TC' => 'Ostrovy Turks a Caicos',
'TD' => 'Čad',
'TF' => 'Francouzská jižní teritoria',
'TG' => 'Togo',
'TH' => 'Thajsko',
'TJ' => 'Tádžikistán',
'TK' => 'Tokelau',
'TL' => 'Východní Timor',
'TM' => 'Turkmenistán',
'TN' => 'Tunisko',
'TO' => 'Tonga',
'TR' => 'Turecko',
'TT' => 'Trinidad a Tobago',
'TV' => 'Tuvalu',
'TW' => 'Tchaj-wan',
'TZ' => 'Tanzanie',
'UA' => 'Ukrajina',
'UG' => 'Uganda',
'UM' => 'Menší odlehlé ostrovy USA',
'US' => 'Spojené státy',
'UY' => 'Uruguay',
'UZ' => 'Uzbekistán',
'VA' => 'Vatikán',
'VC' => 'Svatý Vincenc a Grenadiny',
'VE' => 'Venezuela',
'VG' => 'Britské Panenské ostrovy',
'VI' => 'Americké Panenské ostrovy',
'VN' => 'Vietnam',
'VU' => 'Vanuatu',
'WF' => 'Wallis a Futuna',
'WS' => 'Samoa',
'YE' => 'Jemen',
'YT' => 'Mayotte',
'ZA' => 'Jihoafrická republika',
'ZM' => 'Zambie',
'ZW' => 'Zimbabwe',
);
