<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'B',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'R',
	'S',
	'T',
	'U',
	'V',
	'Y',
];

$languageNames = [
	'sma' => 'Åarjelsaemien gïele',
];
