<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'a',
	'b',
	'ch',
	'd',
	'e',
	'f',
	'g',
	'i',
	'j',
	'k',
	'l',
	'm',
	'n',
	'o',
	'p',
	'r',
	's',
	't',
	'u',
	'v',
	'w',
	'y',
	'z',
];

$languageNames = [
	'ann' => 'Obolo',
];
