<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'B',
	'T',
	'S',
	'E',
	'C',
	'K',
	'X',
	'I',
	'D',
	'Q',
	'R',
	'F',
	'G',
	'O',
	'L',
	'M',
	'N',
	'U',
	'W',
	'H',
	'Y',
];

$languageNames = [
	'aa' => 'Qafar',
];

$countryNames = [
	'DJ' => 'Yabuuti',
	'ER' => 'Eretria',
	'ET' => 'Otobbia',
];
