<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'B',
	'CH',
	'E',
	'F',
	'H',
	'HL',
	'I',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'S',
	'SH',
	'T',
	'U',
	'V',
	'Ʋ',
	'W',
	'Z',
];

$languageNames = [
	'cho' => 'Chahta',
	'en' => 'English',
];

$countryNames = [
	'US' => 'United States',
];
