<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'mus' => 'Mvskoke',
];

$countryNames = [
	'US' => 'United States',
];

$timeUnits = [
	'day-other' => '{0} Nettv',
	'hour-other' => 'Hvse-vkērkv {0}',
	'month-other' => 'Hvse {0}',
	'second-other' => 'Lvplvpkuce {0}',
	'week-other' => 'Nettv-cako {0}',
	'year-other' => 'Ohrolopē {0}',
];
