<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'gn' => 'avañe’ẽ',
];

$countryNames = [
	'AR' => 'Argentína',
	'BO' => 'Bolívia',
	'BR' => 'Brasil',
	'CL' => 'Chíle',
	'CO' => 'Colómbia',
	'EC' => 'Ecuador',
	'EU' => 'Union Européa',
	'EZ' => 'Eurozóna',
	'GF' => 'Guyána Francésa',
	'GL' => 'Groenlandia',
	'GY' => 'Guyana',
	'MX' => 'México',
	'PE' => 'Peru',
	'PY' => 'Paraguai',
	'SR' => 'Surinam',
	'UN' => 'Naciónes Unídas',
	'US' => 'EE. UU.',
	'UY' => 'Uruguay',
	'VE' => 'Venezuéla',
];
