<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'Ä',
	'B',
	'C',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'Ö',
	'P',
	'R',
	'S',
	'T',
	'U',
	'Ü',
	'V',
	'X',
	'Y',
	'Z',
];

$languageNames = [
	'de' => 'Deutänapük',
	'en' => 'Linglänapük',
	'eo' => 'Sperantapük',
	'es' => 'Spanyänapük',
	'fr' => 'Fransänapük',
	'it' => 'Litaliyänapük',
	'ja' => 'Yapänapük',
	'pt' => 'Portugänapük',
	'ru' => 'Rusänapük',
	'vo' => 'Volapük',
	'zh' => 'Tsyinänapük',
];

$countryNames = [
	'BR' => 'Brasilän',
	'CN' => 'Tsyinän',
	'DE' => 'Deutän',
	'ES' => 'Spanyän',
	'FR' => 'Fransän',
	'GB' => 'Regän Pebalöl',
	'GE' => 'Grusiyän',
	'GR' => 'Grikän',
	'IN' => 'Lindän',
	'IT' => 'Litaliyän',
	'JP' => 'Yapän',
	'MX' => 'Mäxikän',
	'NR' => 'Naureän',
	'PT' => 'Portugän',
	'PW' => 'Palauäns',
	'RU' => 'Rusän',
	'US' => 'Lamerikän',
];

$timeUnits = [
	'month-one' => 'mul {0}',
	'month-other' => 'muls {0}',
	'year-one' => 'yel {0}',
	'year-other' => 'yels {0}',
];
