<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'CH',
	'D',
	'E',
	'F',
	'G',
	'I',
	'K',
	'L',
	'LL',
	'M',
	'N',
	'NG',
	'O',
	'P',
	'R',
	'S',
	'SH',
	'T',
	'TR',
	'U',
	'W',
	'Y',
];

$languageNames = [
	'arn' => 'Mapudungun',
];
