<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'CH',
	'E',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'MB',
	'N',
	'ND',
	'NG',
	'NT',
	'O',
	'P',
	'R',
	'RR',
	'S',
	'T',
	'U',
	'V',
	'Y',
	'ʼ',
];

$languageNames = [
	'gn' => 'avañe’ẽ',
];

$countryNames = [
	'AR' => 'Argentína',
	'BO' => 'Bolívia',
	'BR' => 'Brasil',
	'CL' => 'Chíle',
	'CO' => 'Colómbia',
	'EC' => 'Ecuador',
	'EU' => 'Union Européa',
	'EZ' => 'Eurozóna',
	'GF' => 'Guyána Francésa',
	'GL' => 'Groenlandia',
	'GY' => 'Guyana',
	'MX' => 'México',
	'PE' => 'Peru',
	'PY' => 'Paraguai',
	'SR' => 'Surinam',
	'UN' => 'Naciónes Unídas',
	'US' => 'EE. UU.',
	'UY' => 'Uruguay',
	'VE' => 'Venezuéla',
];
