<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'ئ',
	'ا',
	'ب',
	'پ',
	'ت',
	'ج',
	'چ',
	'ح',
	'خ',
	'د',
	'ر',
	'ز',
	'ڕ',
	'ژ',
	'س',
	'ش',
	'ع',
	'غ',
	'ف',
	'ڤ',
	'ق',
	'ک',
	'گ',
	'ل',
	'ڵ',
	'م',
	'ن',
	'ھ',
	'ە',
	'و',
	'ۆ',
	'ۊ',
	'ی',
	'ێ',
];

$languageNames = [
	'eo' => 'ئسپرانتو',
	'sdh' => 'کوردی خوارگ',
];
