<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ar' => 'arabich',
	'ar-001' => 'arabich modern stàndar',
	'en' => 'inglèis',
	'pms' => 'piemontèis',
];

$countryNames = [
	'IT' => 'Italia',
];
