<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ady' => 'adigeo',
	'alt' => 'altái del sur',
	'arp' => 'arapajó',
	'ars' => 'árabe de Néyed',
	'bla' => 'siksiká',
	'eu' => 'vasco',
	'goh' => 'alemán de la alta edad antigua',
	'grc' => 'griego clásico',
	'ht' => 'haitiano',
	'kbd' => 'cabardiano',
	'krc' => 'karachái-bálkaro',
	'lij' => 'genovés',
	'ml' => 'malabar',
	'mni' => 'manipuri',
	'nr' => 'ndebele del sur',
	'nso' => 'sesotho del norte',
	'prg' => 'prusiano antiguo',
	'rm' => 'retorrománico',
	'sd' => 'sindhi',
	'shu' => 'árabe (Chad)',
	'sma' => 'sami del sur',
	'st' => 'sesotho del sur',
	'sw-cd' => 'swahili (Congo)',
	'syr' => 'siríaco',
	'tet' => 'tetun',
	'tyv' => 'tuvano',
	'vec' => 'véneto',
	'wal' => 'walamo',
	'wuu' => 'wu',
	'xal' => 'calmuco',
	'zun' => 'zuni',
];

$currencyNames = [
	'ANG' => 'florín de las Antillas Neerlandesas',
	'BMD' => 'dólar de Bermudas',
	'HTG' => 'gourde haitiano',
	'KZT' => 'tenge kazajo',
	'MWK' => 'kwacha malauí',
	'NIO' => 'córdoba nicaragüense',
	'SLE' => 'leone',
	'SLL' => 'leones (1964—2022)',
	'THB' => 'baht tailandes',
	'UZS' => 'som uzbeko',
	'XXX' => '(unidad de moneda desconocida)',
];

$currencySymbols = [
	'THB' => 'THB',
];

$countryNames = [
	'AC' => 'Isla Ascensión',
	'AX' => 'Islas Åland',
	'BA' => 'Bosnia-Herzegovina',
	'CG' => 'República del Congo',
	'CI' => 'Costa de Marfil',
	'EZ' => 'Eurozona',
	'GB' => 'R. U.',
	'GS' => 'Islas Georgia del Sur y Sándwich del Sur',
	'IC' => 'Islas Canarias',
	'QO' => 'Islas Ultramarinas',
	'RO' => 'Rumania',
	'SA' => 'Arabia Saudita',
	'TL' => 'Timor Oriental',
	'UM' => 'Islas Ultramarinas de EE.UU.',
];

$timeUnits = [
	'day-short-future-one' => 'dentro de {0} día',
	'day-short-future-other' => 'dentro de {0} días',
	'day-short-past-one' => 'hace {0} día',
	'day-short-past-other' => 'hace {0} días',
];
