<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'de' => 'ꄓꇩꉙ',
	'en' => 'ꑱꇩꉙ',
	'es' => 'ꑭꀠꑸꉙ',
	'fr' => 'ꃔꇩꉙ',
	'ii' => 'ꆈꌠꉙ',
	'it' => 'ꑴꄊꆺꉙ',
	'ja' => 'ꏝꀪꉙ',
	'pt' => 'ꁍꄨꑸꉙ',
	'ru' => 'ꊉꇩꉙ',
	'und' => 'ꅉꀋꌠꅇꂷ',
	'zh' => 'ꍏꇩꉙ',
];

$currencyNames = [
	'XXX' => 'ꅉꀋꐚꌠꌋꆀꎆꃀꀋꈁꀐꌠ',
];

$countryNames = [
	'BR' => 'ꀠꑭ',
	'CN' => 'ꍏꇩ',
	'DE' => 'ꄓꇩ',
	'FR' => 'ꃔꇩ',
	'GB' => 'ꑱꇩ',
	'IN' => 'ꑴꄗ',
	'IT' => 'ꑴꄊꆺ',
	'JP' => 'ꏝꀪ',
	'RU' => 'ꊉꇆꌦ',
	'US' => 'ꂰꇩ',
];
