<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'ၵ',
	'ၶ',
	'ၷ',
	'ꧠ',
	'င',
	'ၸ',
	'ꩡ',
	'ꧡ',
	'ꧢ',
	'ၺ',
	'ꩦ',
	'ꩧ',
	'ꩨ',
	'ꩩ',
	'တ',
	'ထ',
	'ၻ',
	'ၼ',
	'ပ',
	'ၽ',
	'ၾ',
	'ၿ',
	'ꧤ',
	'မ',
	'ယ',
	'ရ',
	'လ',
	'ဝ',
	'ႀ',
	'သ',
	'ႁ',
	'ꩮ',
	'ဢ',
];

$languageNames = [
	'shn' => 'တႆး',
];

$countryNames = [
	'MM' => 'မျၢၼ်ႇမႃႇ (မိူင်းမၢၼ်ႈ)',
	'TH' => 'မိူင်းထႆး',
];
