<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'B',
	'C',
	'D',
	'E',
	'F',
	'G',
	'H',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'O',
	'P',
	'Q',
	'R',
	'S',
	'T',
	'U',
	'V',
	'W',
	'X',
	'Y',
	'Z',
];

$languageNames = [
	'ar-001' => 'modernes Hocharabisch',
	'car' => 'karibische Sprache',
	'chb' => 'Chibcha-Sprache',
	'del' => 'Delawarisch',
	'fur' => 'Friulanisch',
	'ha' => 'Hausa',
	'haw' => 'Hawaiianisch',
	'hmn' => 'Miao-Sprache',
	'mus' => 'Muskogee-Sprache',
	'niu' => 'Niueanisch',
	'pag' => 'Pangasinensisch',
	'sh' => 'Serbokroatisch',
	'szl' => 'Schlesisch',
];

$countryNames = [
	'SJ' => 'Svalbard und Jan Mayen',
];
