<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'ހ',
	'ށ',
	'ނ',
	'ރ',
	'ބ',
	'ޅ',
	'ކ',
	'އ',
	'ވ',
	'މ',
	'ފ',
	'ދ',
	'ތ',
	'ލ',
	'ގ',
	'ޏ',
	'ސ',
	'ޑ',
	'ޒ',
	'ޓ',
	'ޔ',
	'ޕ',
	'ޖ',
	'ޗ',
];

$languageNames = [
	'dv' => 'ދިވެހިބަސް',
];

$countryNames = [
	'MV' => 'ދިވެހި ރާއްޖެ',
];
