<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'ا',
	'ب',
	'ت',
	'ث',
	'ج',
	'ح',
	'خ',
	'د',
	'ذ',
	'ر',
	'ز',
	'س',
	'ش',
	'ص',
	'ض',
	'ط',
	'ظ',
	'ع',
	'غ',
	'ف',
	'ق',
	'ك',
	'ل',
	'م',
	'ن',
	'ه',
	'و',
	'ي',
];

$languageNames = [
	'apc' => 'العامية',
];
