<?php
// This file is generated by rebuild.php. Do not edit it directly.

$indexCharacters = [
	'A',
	'B',
	'Ɓ',
	'C',
	'D',
	'Ɗ',
	'E',
	'Ɛ',
	'F',
	'G',
	'I',
	'J',
	'K',
	'L',
	'M',
	'N',
	'Ŋ',
	'O',
	'Ɔ',
	'P',
	'S',
	'T',
	'U',
	'W',
	'Y',
];

$languageNames = [
	'dua' => 'duálá',
];

$countryNames = [
	'CM' => 'Cameroun',
];
