<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'en' => 'angļu',
	'ltg' => 'latgalīšu',
	'lv' => 'latvīšu',
];

$currencyNames = [
	'EUR' => 'eiro',
	'LVL' => 'Latvejis lats',
	'LVR' => 'Latvejis rublis',
];

$countryNames = [
	'LV' => 'Latveja',
];
