<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'az-cyrl' => 'Aserbaidjanesch (kyrillesch Schrëft)',
	'bfi' => 'Brittesch Zeechesprooch',
	'bzs' => 'Brasilianesch Gebärdesprooch',
	'cdz-beng' => 'Koda (bengalesch Schrëft)',
	'de-1901' => 'Däitsch (traditionell Orthografie)',
	'eo-hsistemo' => 'Esperanto (H-System-Orthografie)',
	'eo-xsistemo' => 'Esperanto (X-System-Orthografie)',
	'gsg' => 'Däitsch Gebäerdesprooch',
	'ha-arab' => 'Hausa (arabesch Schrëft)',
	'hoc' => 'Ho',
	'ja-hira' => 'Japanesch (Hiragana-Schrëft)',
	'ja-hrkt' => 'Japanesch (Kana-Schrëft)',
	'ja-kana' => 'Japanesch (Katakana-Schrëft)',
	'ksy-beng' => 'Kharia Thar (bengalesch Schrëft)',
	'kyw-beng' => 'Kurmali (bengalesch Schrëft)',
	'kyw-deva' => 'Kurmali (Devanagari-Schrëft)',
	'lad-hebr' => 'Ladino (hebräesch Schrëft)',
	'lij-mc' => 'Monegassesch',
	'mis' => 'net ënnerstëtzt Sprooch',
	'mjx-beng' => 'Mahali (bengalesch Schrëft)',
	'obt' => 'Albretonesch',
	'pks' => 'Pakistanesch Gebäerdesprooch',
	'sat-beng' => 'Santali (bengalesch Schrëft)',
	'sat-latn' => 'Santali (laténgesch Schrëft)',
	'sat-orya' => 'Santali (Oriya-Schrëft)',
	'sux-latn' => 'Sumeresch (laténgesch Schrëft)',
	'sux-xsux' => 'Sumeresch (sumeresch Schrëft)',
	'syl-beng' => 'Sylheti (bengalesch Schrëft)',
	'tlh-latn' => 'Klingonesch (laténgesch Schrëft)',
	'tlh-piqd' => 'Klingonesch (klingonesch Schrëft)',
	'txo-beng' => 'Toto (bengalesch Schrëft)',
	'xbm' => 'Mëttelbretonesch',
];
