<?php

/** @phpcs-require-sorted-array */
$languageNames = [

	'apc' => 'arabe levantin',
	'az-cyrl' => 'azéri (écriture cyrillique)',
	'bfi' => 'langue des signes britannique',
	'bzs' => 'langue des signes brésilienne',
	'cak' => 'cakchiquel',
	'ccp-beng' => 'changma kodha (écriture bengalaise)',
	'cdz-beng' => 'koda (écriture bengalaise)',
	'cnh' => 'hakha-chin',
	'ctg' => 'chittagonien',
	'de-1901' => 'allemand (orthographe traditionnelle)',
	'eo-hsistemo' => 'espéranto (orthographe du système H)',
	'eo-xsistemo' => 'espéranto (orthographe du système X)',
	'gcr' => 'créole guyanais',
		# used by Wikidata, T262922
	'gsg' => 'langue des signes allemande',
	'gsw' => 'alémanique',
		# T368514
	'gsw-fr' => 'alsacien',
	'ha-arab' => 'hausa (écriture arabe)',
	'hoc' => 'ho',
	'hyw' => 'arménien occidental',
	'ja-hira' => 'japonais (écriture hiragana)',
	'ja-hrkt' => 'japonais (écriture kana)',
	'ja-kana' => 'japonais (écriture katakana)',
	'ksy-beng' => 'kharia thar (écriture bengalaise)',
	'kyw-beng' => 'kurmali (écriture bengalaise)',
	'kyw-deva' => 'kurmali (écriture devanagari)',
	'lad-hebr' => 'judéo-espagnol (écriture hébraïque)',
	'lij-mc' => 'monégasque',
	'mis' => 'langue non prise en charge',
	'mjx-beng' => 'mahali (écriture bengalaise)',
	'mvf' => 'mongol périphérique',
	'nn-hognorsk' => 'norvégien høgnorsk',
	'non-runr' => 'vieux norrois (écriture runique)',
	'nrf-gg' => 'guernésiais',
	'nrf-je' => 'jersiais',
	'obt' => 'breton ancien',
	'pks' => 'langue des signes pakistanaise',
	'pt-ao1990' => 'portugais (accord orthographique de 1990)',
	'pt-colb1945' => 'portugais (accord orthographique de 1945)',
	'rah' => 'rabha',
	'rhg-rohg' => 'rohingya (écriture hanifi rohingya)',
	'rkt' => 'rangpouri',
	'rm-puter' => 'putèr',
	'rm-rumgr' => 'romanche grison',
	'rm-surmiran' => 'surmiran',
	'rm-sursilv' => 'sursilvan',
	'rm-sutsilv' => 'sutsilvan',
	'rm-vallader' => 'vallader',
	'sat-beng' => 'santali (écriture bengalaise)',
	'sat-latn' => 'santali (écriture latine)',
	'sat-orya' => 'santali (écriture oriya)',
	'sia' => 'same d’Akkala',
	'sjk' => 'same de Kemi',
	'sux-latn' => 'sumérien (écriture latine)',
	'sux-xsux' => 'sumérien (écriture sumérienne)',
	'syl-beng' => 'sylheti (écriture bengalaise)',
	'tlh-latn' => 'klingon (écriture latine)',
	'tlh-piqd' => 'klingon (écriture klingon)',
	'txg' => 'tangoute',
	'txo-beng' => 'toto (écriture bengalaise)',
	'xbm' => 'moyen breton',

];
