<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'apc' => 'Levantin arabia',
	'az-cyrl' => 'Azeri (Kyrillinen kirjaimisto)',
	'bfi' => 'Brittiläinen viittomakieli',
	'bzs' => 'Brasilialainen viittomakieli',
	'cak' => 'Kaqchikel',
	'ccp-beng' => 'Chakma (Bengalilainen kirjaimisto)',
	'ctg' => 'Chittagong',
	'gsg' => 'Saksalainen viittomakieli',
	'ha-arab' => 'Hausa (Arabialainen kirjaimisto)',
	'hoc' => 'Ho',
	'ja-hira' => 'Japani (Hiragana-kirjaimisto)',
	'ja-hrkt' => 'Japani (Kana-kirjaimisto)',
	'ja-kana' => 'Japani (Katakana-kirjaimisto)',
	'lad-hebr' => 'Ladino (Heprealainen kirjaimisto)',
	'lij-mc' => 'Monegassi',
	'mis' => 'ei tuettu kieli',
	'nn-hognorsk' => 'Norjan høgnorsk',
	'non-runr' => 'Muinausnorja (Riimukirjaimet)',
	'nrf-gg' => 'Guernésiais',
	'nrf-je' => 'Jèrriais',
	'obt' => 'Muinaisbretoni',
	'pks' => 'Pakistanilainen viittomakieli',
	'rhg-rohg' => 'Rohingya (Hanifi Rohingya -kirjaimisto)',
	'sat-beng' => 'Santali (Bengalilainen kirjaimisto)',
	'sat-latn' => 'Santali (Latinalaiset aakkoset)',
	'sat-orya' => 'Santali (Orijalainen kirjaimisto)',
	'sia' => 'Akkalansaame',
	'sjk' => 'Keminsaame',
	'sux-latn' => 'Sumeri (Latinalaiset aakkoset)',
	'syl-beng' => 'Sylheti (Bengalilainen kirjaimisto)',
	'tlh-latn' => 'Klingon (Latinalaiset aakkoset)',
	'txg' => 'Tanguutti',
	'xbm' => 'Keskibretoni',
];
