<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'apc' => 'levantin arabia',
	'az-cyrl' => 'azeri (kyrillinen kirjaimisto)',
	'bfi' => 'brittiläinen viittomakieli',
	'bzs' => 'brasilialainen viittomakieli',
	'cak' => 'kaqchikel',
	'ccp-beng' => 'chakma (bengalilainen kirjaimisto)',
	'ctg' => 'chittagong',
	'gsg' => 'saksalainen viittomakieli',
	'ha-arab' => 'hausa (arabialainen kirjaimisto)',
	'hoc' => 'ho',
	'ja-hira' => 'japani (hiragana-kirjaimisto)',
	'ja-hrkt' => 'japani (kana-kirjaimisto)',
	'ja-kana' => 'japani (katakana-kirjaimisto)',
	'lad-hebr' => 'ladino (heprealainen kirjaimisto)',
	'lij-mc' => 'monegassi',
	'mis' => 'ei tuettu kieli',
	'nn-hognorsk' => 'norjan høgnorsk',
	'non-runr' => 'muinaisnorja (riimukirjaimet)',
	'nrf-gg' => 'guernésiais',
	'nrf-je' => 'jèrriais',
	'obt' => 'muinaisbretoni',
	'pks' => 'pakistanilainen viittomakieli',
	'rhg-rohg' => 'rohingya (hanifi rohingya -kirjaimisto)',
	'sat-beng' => 'santali (bengalilainen kirjaimisto)',
	'sat-latn' => 'santali (latinalaiset aakkoset)',
	'sat-orya' => 'santali (orijalainen kirjaimisto)',
	'sia' => 'akkalansaame',
	'sjk' => 'keminsaame',
	'sux-latn' => 'sumeri (latinalaiset aakkoset)',
	'syl-beng' => 'sylheti (bengalilainen kirjaimisto)',
	'tlh-latn' => 'klingon (latinalaiset aakkoset)',
	'txg' => 'tanguutti',
	'xbm' => 'keskibretoni',
];
