<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'az-cyrl' => 'Azerbajdzjanska skrivet med kyrilliska bokstäver',
	# Override CLDR name, see T341917/CLDR-16876
	'be' => 'belarusiska',
	'be-tarask' => 'belarusiska (tarasjkevitsa)',
	'bfi' => 'brittiskt teckenspråk',
	'bzs' => 'brasilianskt teckenspråk',
	'cak' => 'cakchiquel',
	'ccp-beng' => 'Chakma med Bengali-skrift',
	'cnh' => 'Hakha-Chin',
	'ctg' => 'chittagoniska',
	'de-1901' => 'Tyska (innan 1996 års reform)',
	'eo-hsistemo' => 'Esperanto (h-system)',
	'eo-xsistemo' => 'Esperanto (x-system)',
	'gsg' => 'tyskt teckenspråk',
	'ha-arab' => 'hausa med arabiska alfabetet',
	'ja-hira' => 'Japanska skrivet i hiragana',
	'ja-hrkt' => 'Japanska skrivet i hiragana och katakana.',
	'ja-kana' => 'Japanska skrivet i katakana',
	'lij-mc' => 'Monegaskiska',
	'mis' => 'andra',
	'mvf' => 'perifer mongoliska',
	'nn-hognorsk' => 'högnorska',
	'non-runr' => 'Fornnordiska skrivet med runor',
	'nrf-gg' => 'Guernésiais',
	'nrf-je' => 'Jèrriais',
	# Override CLDR name, see T281702
	'ps' => 'pashto',
	'pt-ao1990' => 'portugisiska (portugisiska ortografin från 1990)',
	'pt-colb1945' => 'portugisiska (portugisisk-brasilianska ortografin från 1945)',
	'rah' => 'Rabha',
	'rhg-rohg' => 'rohingya på hanifi-alfabetet',
	'rkt' => 'rangpuri',
	'rm-puter' => 'överengadinska',
	'rm-rumgr' => 'Rätoromanska',
	'rm-surmiran' => 'surmeiriska',
	'rm-sursilv' => 'surselviska',
	'rm-sutsilv' => 'sutselviska',
	'rm-vallader' => 'underengadinska',
	'sat-beng' => 'santali med bengalialfabetet',
	'sat-latn' => 'santali med latinska alfabetet',
	'sat-orya' => 'santali med oriyaskrift',
	'sia' => 'akkalasamiska',
	'sjk' => 'kemisamiska',
	'sux-latn' => 'sumeriska med latinska alfabetet',
	'sux-xsux' => 'sumeriska med sumeriska alfabetet',
	'syl-beng' => 'Sylheti med bengali-skrift',
	'tlh-latn' => 'klingon med latinska alfabetet',
	'tlh-piqd' => 'klingon med klingonalfabetet',
];
