<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'az-cyrl' => 'Azerbaijão escrito em escrita cirílica',
	'bfi' => 'Língua de sinais britânica',
	'bzs' => 'Língua Brasileira de Sinais',
	'cak' => 'Kaqchikel',
	'ccp-beng' => 'Changma na escrita bengali',
	'cnh' => 'Hakha-Chin',
	'ctg' => 'Chittagoniano',
	'de-1901' => 'Alemão (antes da reforma de 1996)',
	'eo-hsistemo' => 'Esperanto (h-system)',
	'eo-xsistemo' => 'Esperanto (x-system)',
	'gsg' => 'Língua de sinais alemã',
	'ha-arab' => 'Hauçá em escrita árabe',
	'ja-hira' => 'Japonês escrito em hiragana',
	'ja-hrkt' => 'Japonês escrito em hiragana e katakana',
	'ja-kana' => 'Japonês escrito em katakana',
	'lij-mc' => 'Monegasco',
	'mis' => 'outro',
	'mvf' => 'Língua mongol',
	'non-runr' => 'Nórdico antigo escrito em escrita rúnica',
	'nrf-gg' => 'Guernésiais',
	'nrf-je' => 'Jèrriais',
	'pt-ao1990' => 'Português (Acordo ortográfico de Lingua Portuguesa de 1990)',
	'pt-colb1945' => 'Português (Convenção Ortográfica Português-Brasileiro de 1945)',
	'rah' => 'Rabha',
	'rhg-rohg' => 'Ruáingga em script Hanifi',
	'rkt' => 'Rangpuri',
	'rm-puter' => 'Puter',
	'rm-rumgr' => 'Romanche',
	'rm-surmiran' => 'Surmiran',
	'rm-sursilv' => 'Sursilvan',
	'rm-sutsilv' => 'Sutsilvan',
	'rm-vallader' => 'Vallader',
	'sat-beng' => 'Santali na escrita bengali',
	'sat-latn' => 'Santali em escrita latina',
	'sat-orya' => 'Santali na escrita oriá',
	'sux-latn' => 'Sumério em escrita latina',
	'sux-xsux' => 'Sumério em escrita Suméria',
	'syl-beng' => 'Sylheti na escrita bengali',
	'tlh-latn' => 'Klingon em escrita latina',
	'tlh-piqd' => 'Klingon em escrita Klingon',
];
