<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'az-cyrl' => 'Tiếng Azerbaijan (chữ Kirin)',
	'bfi' => 'Ngôn ngữ ký hiệu Anh',
	'cak' => 'Tiếng Kaqchikel',
	'ccp-beng' => 'Tiếng Chakma (chữ Bengal)',
	'cnh' => 'Tiếng Hakha–Chin',
	'ctg' => 'Tiếng Chittagong',
	'de-1901' => 'Tiếng Đức (trước cải cách năm 1996)',
	'eo-hsistemo' => 'Quốc tế ngữ (hệ thống h)',
	'eo-xsistemo' => 'Quốc tế ngữ (hệ thống x)',
	'gsg' => 'Ngôn ngữ ký hiệu Đức',
	'ha-arab' => 'Tiếng Hausa (chữ Ả Rập)',
	'ja-hira' => 'Tiếng Nhật (chữ Hiragana)',
	'ja-hrkt' => 'Tiếng Nhật (cả chữ Hiragana lẫn Katakana)',
	'ja-kana' => 'Tiếng Nhật (chữ Katakana)',
	'lij-mc' => 'Tiếng Monaco',
	'mis' => 'khác',
	'mvf' => 'Tiếng Nội Mông',
	'nn-hognorsk' => 'Tiếng Høgnorsk',
	'non-runr' => 'Tiếng Bắc Âu cổ (chữ Rune)',
	'nrf-gg' => 'Tiếng Guernsey',
	'nrf-je' => 'Tiếng Jersey',
	'pt-ao1990' => 'Tiếng Bồ Đào Nha (Thỏa thuận Chính tả Tiếng Bồ Đào Nhà năm 1990)',
	'pt-colb1945' => 'Tiếng Bồ Đào Nha (Thỏa thuận Chính tả Tiếng Bồ Đào Nha năm 1945)',
	'rah' => 'Tiếng Rabha',
	'rhg-rohg' => 'Tiếng Rohingya (chữ Hanif)',
	'rkt' => 'Tiếng Rangpur',
	'rm-puter' => 'Tiếng Putèr',
	'rm-rumgr' => 'tiếng Rumantsch Grischun',
	'rm-surmiran' => 'Tiếng Surmeir',
	'rm-sursilv' => 'Tiếng Surselva',
	'rm-sutsilv' => 'Tiếng Sutselva',
	'rm-vallader' => 'Tiếng Vallader',
	'sat-beng' => 'Tiếng Santal (chữ Bengal)',
	'sat-latn' => 'Tiếng Santal (chữ Latinh)',
	'sat-orya' => 'Tiếng Santal (chữ Oriya)',
	'sux-latn' => 'Tiếng Sumer (chữ Latinh)',
	'sux-xsux' => 'Chữ Sumer (chữ Sumer)',
	'syl-beng' => 'Tiếng Sylhet (chữ Bengal)',
	'tlh-latn' => 'Tiếng Klingon (chữ Latinh)',
	'tlh-piqd' => 'Tiếng Klingon (chữ Klingon)',
];
