<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'az-cyrl' => 'Bahasa Azerbaijan (tulisan Sirilik)',
	'bfi' => 'Bahasa Isyarat British',
	'bzs' => 'Bahasa Isyarat Brazil',
	'cak' => 'Kaqchikel',
	'ccp-beng' => 'Chakma dalam tulisan Bengali',
	'cnh' => 'Hakha-Chin',
	'de-1901' => 'Jerman (sebelum pembaharuan 1996)',
	'enm' => 'Inggeris Pertengahan',
	'eo-hsistemo' => 'Esperanto (sistem h)',
	'eo-xsistemo' => 'Esperanto (sistem x)',
	'frm' => 'Perancis Pertengahan',
	'gsg' => 'Bahasa Isyarat Jerman',
	'ha-arab' => 'Hausa dalam tulisan Arab',
	'hoc' => 'Ho',
	'ja-hira' => 'Jepun ditulis dalam Hiragana',
	'ja-hrkt' => 'Jepun ditulis dalam Hiragana dan Katakana',
	'ja-kana' => 'Jepun ditulis dalam Katakana',
	'lij-mc' => 'Monégasque',
	'mis' => 'lain',
	'nrf-gg' => 'Guernésiais',
	'nrf-je' => 'Jèrriais',
	'rah' => 'Rabha',
	'rhg-rohg' => 'Rohingya dalam tulisan Hanifi',
	'rkt' => 'Rangpuri',
	'rm-puter' => 'Puter',
	'rm-vallader' => 'Vallader',
	'sat-latn' => 'Santali dalam tulisan Rumi',
	'sat-orya' => 'Santali dalam tulisan Oriya',
	'syl-beng' => 'Sylheti dalam tulisan Bengali',
	'tlh-latn' => 'Klingon dalam tulisan Rumi',
	'tlh-piqd' => 'Klingon dalam tulisan Klingon',
];
