<?php

/** @phpcs-require-sorted-array */
$languageNames = [
	'apc' => 'Árabe levantino',
	'az-cyrl' => 'Azerbaiyano (cirílico)',
	'bfi' => 'Lenguaje de señas británico',
	'bzs' => 'Lenguaje de señas brasileño',
	'cak' => 'Kaqchikel',
	'ccp-beng' => 'Chakma (escritura bengalí)',
	'cnh' => 'Hakha-Chin',
	'ctg' => 'Chittagoniano',
	'de-1901' => 'Alemán (ortografía tradicional)',
	'eo-hsistemo' => 'Esperanto (ortografía del sistema de haches)',
	'eo-xsistemo' => 'Esperanto (ortografía del sistema de equis)',
	'gsg' => 'Lengua de señas alemana',
	'ha-arab' => 'Hausa (árabe)',
	'hoc' => 'Ho',
	'ja-hira' => 'Japonés (escritura hiragana)',
	'ja-hrkt' => 'Japonés (escritura Kana)',
	'ja-kana' => 'Japonés (escritura katakana)',
	'lad-hebr' => 'Ladino (escritura hebrea)',
	'lij-mc' => 'Monegasco',
	'mis' => 'idioma no admitido',
	'mvf' => 'mongol periférico',
	'nn-hognorsk' => 'noruego høgnorsk',
	'non-runr' => 'Nórdico antiguo (escritura rúnica)',
	'nrf-gg' => 'Guernés',
	'nrf-je' => 'jerseyés',
	'obt' => 'bretón antiguo',
	'pks' => 'Lengua de señas de Pakistán',
	'pt-ao1990' => 'Portugués (ortografía de 1990)',
	'pt-colb1945' => 'Portugués (ortografía de 1945)',
	'rah' => 'rabha',
	'rhg-rohg' => 'Rohinyá (escritura Hanifi Rohinyá)',
	'rkt' => 'Rangpuri',
	'sat-latn' => 'Santali (escritura latina)',
	'sux-xsux' => 'Sumerio (escritura sumeria)',
	'tlh-latn' => 'Klingon (escritura latina)',
	'tlh-piqd' => 'Klingon (escritura klingon)',
	'txg' => 'Tángut',
	'xbm' => 'Bretón medio',
];
