<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ace' => 'Aceh-Sprache',
	'ach' => 'Acholi-Sprache',
	'ar-001' => 'Modernes Hocharabisch',
	'ars' => 'Nadschd-Arabisch',
	'bas' => 'Basaa-Sprache',
	'bik' => 'Bikol-Sprache',
	'bin' => 'Bini-Sprache',
	'chb' => 'Chibcha-Sprache',
	'de-ch' => 'Schweizer Hochdeutsch',
	'din' => 'Dinka-Sprache',
	'fan' => 'Pangwe-Sprache',
	'gba' => 'Gbaya-Sprache',
	'kmb' => 'Kimbundu-Sprache',
	'mus' => 'Muskogee-Sprache',
	'nl-be' => 'Flämisch',
	'prg' => 'Altpreussisch',
	'zh-hans' => 'Chinesisch (vereinfacht)',
	'zh-hant' => 'Chinesisch (traditionell)',
];

$currencyNames = [
	'BYN' => 'Weissrussischer Rubel',
	'BYR' => 'Weissrussischer Rubel (2000–2016)',
	'STN' => 'São-toméischer Dobra (2018)',
];

$countryNames = [
	'BN' => 'Brunei',
	'BW' => 'Botswana',
	'CV' => 'Kapverden',
	'GB' => 'Grossbritannien',
	'QO' => 'Äusseres Ozeanien',
	'SB' => 'Salomon-Inseln',
	'TL' => 'Osttimor',
	'ZW' => 'Zimbabwe',
];
