<?php

$languageNames = array(
	'wal' => 'Walamo',
);

$currencyNames = array(
	'BYB' => 'Belarusian New Rouble (1994–1999)',
	'ILR' => 'Israeli Shekel (1980–1985)',
	'ILS' => 'Israeli New Shekel',
	'LVR' => 'Latvian Rouble',
	'MVP' => 'Maldivian Rupee',
	'RUR' => 'Russian Rouble (1991–1998)',
	'SCR' => 'Seychelles rupee',
	'SHP' => 'Saint Helena Pound',
	'STD' => 'São Tomé and Príncipe Dobra',
	'TJR' => 'Tajikistani Rouble',
	'TTD' => 'Trinidad and Tobago Dollar',
	'XOF' => 'CFA franc BCEAO',
);

$currencySymbols = array(
	'BYB' => 'BYB',
	'ILS' => '₪',
	'LVR' => 'LVR',
	'RUR' => 'RUR',
	'SCR' => 'SCR',
	'SHP' => 'SHP',
	'STD' => 'STD',
	'TJR' => 'TJR',
	'TTD' => 'TTD',
	'XOF' => 'CFA',
);

$countryNames = array(
	'AG' => 'Antigua and Barbuda',
	'BA' => 'Bosnia and Herzegovina',
	'BL' => 'Saint Barthélemy',
	'EA' => 'Ceuta and Melilla',
	'GB' => 'UK',
	'KN' => 'Saint Kitts and Nevis',
	'LC' => 'Saint Lucia',
	'MF' => 'Saint Martin',
	'PM' => 'Saint Pierre and Miquelon',
	'SH' => 'Saint Helena',
	'SJ' => 'Svalbard and Jan Mayen',
	'ST' => 'São Tomé and Príncipe',
	'TC' => 'Turks and Caicos Islands',
	'TT' => 'Trinidad and Tobago',
	'US' => 'US',
	'WF' => 'Wallis and Futuna',
);

$timeUnits = array(
	'day-narrow-future-one' => '+{0} day',
	'day-narrow-future-other' => '+{0} days',
	'day-narrow-past-one' => '-{0} day',
	'day-narrow-past-other' => '-{0} days',
	'day-short-future-one' => 'in {0} day',
	'day-short-future-other' => 'in {0} days',
	'day-short-past-one' => '{0} day ago',
	'day-short-past-other' => '{0} days ago',
	'hour-narrow-future-one' => '+{0} h',
	'hour-narrow-future-other' => '+{0} h',
	'hour-narrow-past-one' => '-{0} h',
	'hour-narrow-past-other' => '-{0} h',
	'minute-narrow-future-one' => '+{0} m',
	'minute-narrow-future-other' => '+{0} m',
	'minute-narrow-past-one' => '-{0} m',
	'minute-narrow-past-other' => '-{0} m',
	'month-narrow-future-one' => '+{0} mo.',
	'month-narrow-future-other' => '+{0} mo.',
	'month-narrow-past-one' => '-{0} mo.',
	'month-narrow-past-other' => '-{0} mo.',
	'quarter-narrow-future-one' => '+{0} Q',
	'quarter-narrow-future-other' => '+{0} Q',
	'quarter-narrow-past-one' => '-{0} Q',
	'quarter-narrow-past-other' => '-{0} Q',
	'second-narrow-future-one' => '+{0} s',
	'second-narrow-future-other' => '+{0} s',
	'second-narrow-past-one' => '-{0} s ago',
	'second-narrow-past-other' => '-{0} s ago',
	'week-narrow-future-one' => '+{0} wk.',
	'week-narrow-future-other' => '+{0} wk.',
	'week-narrow-past-one' => '-{0} wk.',
	'week-narrow-past-other' => '-{0} wk.',
	'year-narrow-future-one' => '+{0} yr.',
	'year-narrow-future-other' => '+{0} yr.',
	'year-narrow-past-one' => '-{0} yr.',
	'year-narrow-past-other' => '-{0} yr.',
);
