<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'en' => 'taglinzit',
	'rif' => 'Tarifit',
];

$countryNames = [
	'MA' => 'Lmuɣrib',
	'TR' => 'Ṭurkya',
];
