<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ach' => 'Acholi-Sprache',
	'bik' => 'Bikol-Sprache',
	'chb' => 'Chibcha-Sprache',
	'din' => 'Dinka-Sprache',
	'fan' => 'Pangwe-Sprache',
	'gba' => 'Gbaya-Sprache',
	'prg' => 'Altpreussisch',
	'rhg' => 'Rohingya',
	'tgx' => 'Tagisch',
];

$currencyNames = [
	'BYN' => 'Weissrussischer Rubel',
	'BYR' => 'Weissrussischer Rubel (2000–2016)',
	'STN' => 'São-toméischer Dobra (2018)',
];

$countryNames = [
	'BN' => 'Brunei',
	'BW' => 'Botswana',
	'CV' => 'Kapverden',
	'QO' => 'Äusseres Ozeanien',
	'SB' => 'Salomon-Inseln',
	'TL' => 'Osttimor',
	'ZW' => 'Zimbabwe',
];
