<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'de' => 'Jeman',
	'de-at' => 'Austria Jeman',
	'de-ch' => 'Swis Jeman',
	'en' => 'Inglis',
	'en-au' => 'Australian Inglis',
	'en-ca' => 'Kenedien Inglis',
	'en-gb' => 'Britis Inglis',
	'en-us' => 'Amerikan Inglis',
	'es' => 'Spenis',
	'es-419' => 'Saut Amerikan Spenis',
	'es-es' => 'Spenis (Spein)',
	'es-mx' => 'Meksikan Spenis',
	'fr' => 'Frens',
	'fr-ca' => 'Kenedien Frens',
	'fr-ch' => 'Swis Frens',
	'it' => 'Italien',
	'ja' => 'Japanis',
	'pt' => 'Potigis',
	'pt-br' => 'Brasilien Potigis',
	'pt-pt' => 'Yurop Potigis',
	'ru' => 'Rasien',
	'tpi' => 'Tok Pisin',
	'und' => 'Tok ples i no stap',
	'zh' => 'Sainis',
	'zh-hans' => 'Isipela Sainis',
	'zh-hant' => 'Tredisinol Sainis',
];

$countryNames = [
	'BR' => 'Brasil',
	'CN' => 'Saina',
	'DE' => 'Jemani',
	'FR' => 'Frans',
	'GB' => 'Yunaited Kingdom',
	'IN' => 'India',
	'IT' => 'Itali',
	'PG' => 'Papua Niugini',
];
