<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'de' => 'Tiamana',
	'de-at' => 'Tiamana Atiria',
	'de-ch' => 'Tiamana Ōkawa Huiterangi',
	'en' => 'Ingarihi',
	'en-au' => 'Ingarihi Ahitereiriana',
	'en-ca' => 'Ingarihi Kānata',
	'en-gb' => 'Ingarihi Piritene',
	'en-us' => 'Ingarihi Amerikana',
	'es' => 'Paniora',
	'es-419' => 'Paniora Amerika ki te Tonga',
	'es-es' => 'Paniora Uropi',
	'es-mx' => 'Paniora Mēhikana',
	'fr' => 'Wīwī',
	'fr-ca' => 'Wīwī Kānata',
	'fr-ch' => 'Wīwī Huiterangi',
	'it' => 'Ītariana',
	'ja' => 'Hapanihi',
	'mi' => 'te reo Māori',
	'pt' => 'Pōtikī',
	'pt-br' => 'Pōtikī Parahi',
	'pt-pt' => 'Pōtikī Uropi',
	'ru' => 'Ruhiana',
	'und' => 'Reo Tē Mōhiotia',
	'zh' => 'Hainamana',
	'zh-hans' => 'Hainamana Māmā',
	'zh-hant' => 'Hainamana Tukuiho',
];

$currencyNames = [
	'BRL' => 'Real Parahi',
	'CNY' => 'Yuan Haina',
	'EUR' => 'Euro',
	'GBP' => 'Pāuna Piritene',
	'INR' => 'Rupī Iniana',
	'JPY' => 'Yen Hapanihi',
	'NZD' => 'Tāra o Aotearoa',
	'RUB' => 'Rūpera Ruhiana',
	'USD' => 'Tāra US',
	'XXX' => 'Moni Tē Mōhiotia',
];

$currencySymbols = [
	'JPY' => '¥',
	'NZD' => '$',
];

$countryNames = [
	'BR' => 'Parahi',
	'CN' => 'Haina',
	'DE' => 'Tiamana',
	'FR' => 'Wīwī',
	'GB' => 'Hononga o Piritene',
	'IN' => 'Inia',
	'IT' => 'Itāria',
	'JP' => 'Hapani',
	'MK' => 'Makerōnia ki te Raki',
	'NZ' => 'Aotearoa',
	'RU' => 'Rūhia',
	'US' => 'Hononga o Amerika',
];
