<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'de' => 'Jérman',
	'de-at' => 'Jérman Austria',
	'de-ch' => 'Jérman Swiss Luhur',
	'en' => 'Inggris',
	'en-au' => 'Inggris Australia',
	'en-ca' => 'Inggris Kanada',
	'en-us' => 'Inggris Amerika',
	'es' => 'Spanyol',
	'es-419' => 'Spanyol Amérika Latin',
	'es-es' => 'Spanyol Éropa',
	'es-mx' => 'Spanyol Méksiko',
	'fr' => 'Prancis',
	'fr-ca' => 'Prancis Kanada',
	'fr-ch' => 'Prancis Swiss',
	'it' => 'Italia',
	'ja' => 'Jepang',
	'pt' => 'Portugis',
	'pt-br' => 'Portugis Brasil',
	'pt-pt' => 'Portugis Éropa',
	'ru' => 'Rusia',
	'su' => 'Basa Sunda',
	'und' => 'Basa teu dikenal',
	'zh' => 'Tiongkok',
	'zh-hans' => 'Tiongkok Sederhana',
	'zh-hant' => 'Tiongkok Tradisional',
];

$currencyNames = [
	'BRL' => 'Real Brasil',
	'CNY' => 'Yuan Tiongkok',
	'EUR' => 'Euro',
	'GBP' => 'Pound Inggris',
	'IDR' => 'Rupee Indonésia',
	'INR' => 'Rupee India',
	'JPY' => 'Yén Jepang',
	'RUB' => 'Rubel Rusia',
	'USD' => 'Dolar A.S.',
	'XXX' => 'Mata Uang Teu Dikenal',
];

$currencySymbols = [
	'IDR' => 'Rp',
	'JPY' => '¥',
	'USD' => '$',
];

$countryNames = [
	'BR' => 'Brasil',
	'CN' => 'Tiongkok',
	'DE' => 'Jérman',
	'FR' => 'Prancis',
	'GB' => 'Britania Raya',
	'ID' => 'Indonesia',
	'IN' => 'India',
	'IT' => 'Italia',
	'JP' => 'Jepang',
	'RU' => 'Rusia',
	'US' => 'Amérika Sarikat',
];
