<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ab' => 'abcazo',
	'ace' => 'achineze',
	'ada' => 'adangme',
	'ady' => 'adiga',
	'af' => 'afregan',
	'agq' => 'aghem',
	'ain' => 'ainu',
	'ak' => 'akan',
	'ale' => 'aleutian',
	'am' => 'amàrego',
	'an' => 'aragoneze',
	'anp' => 'angika',
	'ar' => 'àrabo',
	'ar-001' => 'àrabo moderno',
	'arp' => 'arapaho',
	'sq' => 'albaneze',
	'vec' => 'Veneto',
];
