<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ar-001' => 'Modern Standard Arabic',
	'de-at' => 'Austrian German',
	'de-ch' => 'Swiss High German',
	'en-au' => 'Australian English',
	'en-ca' => 'Canadian English',
	'en-gb' => 'British English',
	'en-us' => 'American English',
	'es-419' => 'Latin American Spanish',
	'es-es' => 'European Spanish',
	'es-mx' => 'Mexican Spanish',
	'fa-af' => 'Dari',
	'fr-ca' => 'Canadian French',
	'fr-ch' => 'Swiss French',
	'nds-nl' => 'West Low German',
	'nl-be' => 'Flemish',
	'pt-br' => 'Brazilian Portuguese',
	'pt-pt' => 'European Portuguese',
	'ro-md' => 'Moldavian',
	'sw-cd' => 'Congo Swahili',
	'zh-hans' => 'Simplified Chinese',
	'zh-hant' => 'Traditional Chinese',
];

$countryNames = [
	'BL' => 'St Barthélemy',
	'KN' => 'St Kitts & Nevis',
	'LC' => 'St Lucia',
	'MF' => 'St Martin',
	'PM' => 'St Pierre & Miquelon',
	'SH' => 'St Helena',
	'VC' => 'St Vincent & the Grenadines',
];

$timeUnits = [
	'day-narrow-future-one' => 'in {0} day',
	'day-narrow-future-other' => 'in {0} days',
	'day-narrow-past-one' => '{0} day ago',
	'day-narrow-past-other' => '{0} days ago',
];
