<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'en' => 'ingles',
	'pap' => 'Papiamentu',
];

$countryNames = [
	'AW' => 'Aruba',
	'CW' => 'Kòrsou',
	'TR' => 'Turkia',
];
