<?php
// This file is generated by rebuild.php. Do not edit it directly.

$languageNames = [
	'ar' => 'عرب',
	'de' => 'جرمان',
	'en' => 'ايغضريس',
	'fr' => 'ڤرنچيس',
	'hi' => 'هيندي',
	'id' => 'إندونيسيا',
	'it' => 'إيطاليا',
	'ja' => 'جڤون',
	'jv' => 'جاو',
	'ml' => 'مالايالم',
	'ms' => 'بهاس ملايو',
	'nl' => 'بلندا',
	'pl' => 'ڤولندا',
	'pt' => 'ڤورتوݢيس',
	'ta' => 'تاميل',
	'tr' => 'ترکيا',
	'und' => 'بهاس تيدق دکتاهوءي',
	'zh' => 'چينا',
	'zh-hans' => 'چينا ريڠکس',
	'zh-hant' => 'چينا تراديسيونل',
	'zxx' => 'تيدق کندوڠن ليڠݢوٴيستيک',
];

$currencyNames = [
	'BND' => 'دولر بروني',
	'GBP' => 'ڤاٴون ستيرليڠ بريتيش',
	'IDR' => 'روڤياە إندونيسيا',
	'MYR' => 'ريڠݢيت مليسيا',
	'SGD' => 'دولر سيڠاڤورا',
	'XXX' => 'مات واڠ تيدق دکتاهوءي',
];

$currencySymbols = [
	'MYR' => 'RM',
];

$countryNames = [
	'BN' => 'بروني',
	'BR' => 'البرازيل',
	'CN' => 'چينا',
	'DE' => 'جرمان',
	'FR' => 'ڤرنچيس',
	'ID' => 'إندونيسيا',
	'IN' => 'اينديا',
	'IT' => 'إيطاليا',
	'JP' => 'جڤون',
	'MY' => 'مليسيا',
	'SA' => 'عرب سعودي',
	'SG' => 'سيڠاڤورا',
	'TH' => 'تايلان',
	'TW' => 'تايوان',
	'US' => 'اميريک شريکت',
];

$timeUnits = [
	'day-future-other' => 'دالم {0} هاري',
	'day-past-other' => '{0} هاري لالو',
	'hour-future-other' => 'دالم {0} جم',
	'hour-past-other' => '{0} جم لالو',
	'minute-future-other' => 'دالم {0} مينيت',
	'minute-other' => '{0} مينيت',
	'minute-past-other' => '{0} مينيت لالو',
	'month-future-other' => 'دالم {0} بولن',
	'month-past-other' => '{0} بولن لالو',
	'second-future-other' => 'دالم {0} ساعت',
	'second-past-other' => '{0} ساعت لالو',
	'week-future-other' => 'دالم {0} ميڠݢو',
	'week-past-other' => '{0} ميڠݢو لالو',
	'year-future-other' => 'دالم {0} تاهون',
	'year-other' => '{0} تاهون',
	'year-past-other' => '{0} تاهون لالو',
];
