<?php

use MediaWiki\Extension\CLDR\PhpFileWriter;

/**
 * @license GPL-2.0-or-later
 *
 * @covers MediaWiki\Extension\CLDR\PhpFileWriter
 */
class PhpFileWriterTest extends MediaWikiIntegrationTestCase {

	/**
	 * @dataProvider provideSavePhp
	 * @param array $data
	 * @param string $expectedText
	 */
	public function testSavePhp( $data, $expectedText ) {
		$tmpFile = tempnam( sys_get_temp_dir(), 'testSavePhp' );
		$writer = new PhpFileWriter();
		$writer->savephp( $data, $tmpFile );
		$this->assertEquals(
			$expectedText,
			file_get_contents( $tmpFile )
		);
	}

	public function provideSavePhp() {
		return [
			'no data' => [ [], '' ],
			'basic' => [
				[
					'testEmpty' => [],
					'testStr' => [ 'foo' ],
					'testList' => [ 'foo' => 'bar' ],
				],
				<<<'EOT'
				<?php
				// This file is generated by rebuild.php. Do not edit it directly.

				$testStr = [
					'foo',
				];

				$testList = [
					'foo' => 'bar',
				];

				EOT,
			],
		];
	}

}
